### PR TITLE
Fix relatior error when extra user roles field has no value

### PR DESCRIPTION
**Pull request by marceloneppel**
## Proposal
Jira ticket: [DPE-1233](https://warthogs.atlassian.net/browse/DPE-1233)

The PgBouncer charm failed when the other charm haven't requested any extra user roles (so the field is None and due to that it cannot be iteraded). It was happening when relating to the data-integrator and specifying only it's required config (database name), but it would happen with any other charm that don't request extra user roles through the relation.

Fixed that by using an empty value instead of none, to be consistent with the check the PgBouncer charm make.

## Context
Also, a mention to `lib-check` was removed from `release.yaml` (currently the release process is [broken](https://github.com/canonical/pgbouncer-k8s-operator/actions/runs/4114649468/workflow)).

## Release Notes
Fix relatior error when extra user roles field has no value.

## Testing
Added a test where the charm is related to the data integrator.

[DPE-1233]: https://warthogs.atlassian.net/browse/DPE-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dragomirp — APPROVED** [review]

**Review by taurus-forever — APPROVED** [review]
Strange, the PR is not merged but `data-integrator` is happy already: 
https://github.com/canonical/data-integrator/actions/runs/4082516930 
:-)

LGTM!

**Comment by marceloneppel** [comment]
> Strange, the PR is not merged but `data-integrator` is happy already: https://github.com/canonical/data-integrator/actions/runs/4082516930 :-)
> 
> LGTM!

I think the data integrator is just testing PostgreSQL, not PgBouncer.

**Comment by taurus-forever** [comment]
> I think the data integrator is testing only PostgreSQL, not PgBouncer.

Discussed this with Mykola, he believes both PostgreSQL and PgBouncer should be relatable with data-integrator.
I have created a TODO ticket to add such tests [DPE-1286](https://warthogs.atlassian.net/browse/DPE-1286).
Should we reopen [DPE-1233](https://warthogs.atlassian.net/browse/DPE-1233)?

**Comment by marceloneppel** [comment]
> > I think the data integrator is testing only PostgreSQL, not PgBouncer.
> 
> Discussed this with Mykola, he believes both PostgreSQL and PgBouncer should be relatable with data-integrator. I have created a TODO ticket to add such tests [DPE-1286](https://warthogs.atlassian.net/browse/DPE-1286). Should we reopen [DPE-1233](https://warthogs.atlassian.net/browse/DPE-1233)?

I think we should reopen it or create another ticket if we find new issues when relating both charms. Have you found any other issue? So we can plan to work on it.

**Pull request merged**
